dist: bionic
language: node_js
node_js:
  - 10.14.2
  - 10
  - 12
cache:
  yarn: true
# addons:
#   apt:
#     packages:
#       - php7.2-cli
#       - php7.2-mysql
# services:
#   - mysql

before_script:
  - yarn prepare-links
